import type { Locale } from '@/i18n';

export function getViewerLabels(locale: Locale) {
  return locale === 'ja'
    ? {
        section: '断面',
        display: '表示',
        allStories: '全階',
        currentStory: '現階',
        story: '階',
        zRange: 'Z範囲',
        members: '部材',
        columns: '柱',
        beams: '梁',
        walls: '壁',
        slabs: 'スラブ',
        mode: 'モード',
        axis: '軸',
        position: '位置',
        thickness: '厚み',
        engine: '形状',
        off: 'OFF',
        clip: '片側',
        slice: 'スライス',
        box: 'ボックス',
        native: '標準',
        opencascade: 'OpenCascade',
        runtimeMissing: '外部ランタイム未検出',
        measure: '計測',
        measureClear: 'クリア',
        measureHint: '2点をクリックして距離を計測（端点優先スナップ）',
        measureDistance: '距離',
        measureLength: '長さ',
        analysisResults: '解析結果',
        showAnalysisResults: '解析結果を表示',
        deformationScale: '変形倍率',
        utilization: '検定比',
        analysisWarnings: '警告',
        axial: '軸力',
        moment: '曲げ My/Mz',
      }
    : {
        section: 'Section',
        display: 'Display',
        allStories: 'All',
        currentStory: 'Current',
        story: 'Story',
        zRange: 'Z Range',
        members: 'Members',
        columns: 'Columns',
        beams: 'Beams',
        walls: 'Walls',
        slabs: 'Slabs',
        mode: 'Mode',
        axis: 'Axis',
        position: 'Position',
        thickness: 'Thickness',
        engine: 'Geometry',
        off: 'OFF',
        clip: 'Clip',
        slice: 'Slice',
        box: 'Box',
        native: 'Native',
        opencascade: 'OpenCascade',
        runtimeMissing: 'Runtime not detected',
        measure: 'Measure',
        measureClear: 'Clear',
        measureHint: 'Click two points to measure distance (snaps to endpoints)',
        measureDistance: 'Distance',
        measureLength: 'Length',
        analysisResults: 'Analysis results',
        showAnalysisResults: 'Show analysis results',
        deformationScale: 'Deformation scale',
        utilization: 'Utilization',
        analysisWarnings: 'Warnings',
        axial: 'Axial',
        moment: 'Moment My/Mz',
      };
}

export type ViewerLabels = ReturnType<typeof getViewerLabels>;
